### PR TITLE
Small updates to add flexability

### PR DESCRIPTION
**Pull request by SteveAquino**
I've added an attr_accessor to WepayRails::Payments::Gateway to allow a user to retrieve the account_id of an authorized user for later use.  This is useful for allowing multiple accounts to be authorized in one Rails app.

I also noticed that WepayRails includes api/checkout_methods but not api/account_methods, so I've included account_methods by default to allow easy account creation and manipulation.

I've also updated the VERSION file and regenerated the gemspec to match.  I have not set up actual tests by I've been using my version of the gem and it is working perfectly.  Please let me know if there's any issues.

### CODE REVIEW

**Comment by adamthedeveloper** [comment]
FANTASTIC!  All I ask is add an entry to the Wiki showing us all how to use your new feature.  As soon as that is in place, I'll pull your changes and send you a rubymine key!

Thanks!!

Adam

**Comment by SteveAquino** [comment]
Ok added the wiki page and made another minor adjustment.  I had to 
update the gemspec and version again for the change but I made typo in 
the commit message; it still says version 2.2.6 but it is now 2.2.7, so 
I apologize for any confusion.

**Comment by adamthedeveloper** [comment]
Hi Steve,

  I went into the wiki in the wepay-rails project, and I saw no
additional page(s) for your additions. Can you add them here?
https://github.com/adamthedeveloper/wepay-rails/wiki

Enjoy!

Adam

On Fri, May 25, 2012 at 9:33 PM, Steve Aquino
reply@reply.github.com
wrote:

> Ok added the wiki page and made another minor adjustment.  I had to
> update the gemspec and version again for the change but I made typo in
> the commit message; it still says version 2.2.6 but it is now 2.2.7, so
> I apologize for any confusion.
> 
> On 05/25/2012 03:49 PM, Adam Medeiros wrote:
> 
> > FANTASTIC!  All I ask is add an entry to the Wiki showing us all how to use your new feature.  As soon as that is in place, I'll pull your changes and send you a rubymine key!
> > 
> > Thanks!!
> > 
> > Adam
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/adamthedeveloper/wepay-rails/pull/10#issuecomment-5942081
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/adamthedeveloper/wepay-rails/pull/10#issuecomment-5944303

## 

A.R. Medeiros

**Comment by SteveAquino** [comment]
Ok sorry about that, I've never added a Wiki page to a group project - I 
thought I had to add it on mine and it would merge when it was pulled 
into the main project.  In any case I've added the page to the proper 
place.  One thing though:  I can get everything to work properly, but 
when I try to run a unit test, there are some weird bugs: calling 
create_account results in like 10-20 creations of the same account, but 
everything works as expected from the console as well as in development, 
so I'm not sure what's going on there.  Running bundle exec rake test 
from the wepay-rails directory results in a loading error that I haven't 
yet taken the time to dive into yet.  As I said before, I'm currently 
using my version of the gem and having no issues beyond the test suite.  
I'm adamant about TDD, so it bothers me that my tests are running 
weird.  The changes I made are pretty trivial, so hopefully it's just 
something silly on my test suite I'm not seeing.

Thanks much for the RubyMine license!  I'm using Aptana Studio now and 
it's very buggy, so hopefully a more popular IDE will be better!

**Comment by adamthedeveloper** [comment]
Steve,

  Give rubymine some time. It's the best IDE for Rubyists in my
opinion and takes hours off of my projects (once you find the tools
within it that are awesome - merge tool, control-clicking methods and
classes for fast reading, running test suite within it, etc.).

  I am a huge fan of TDD too. I'll pull down your changes this weekend
sometime and take a look myself to see what is happening and get back
to you.

  Thanks for the wikipage - it helps the community a lot! I'll get you
into the list of contributors soon!

Adam

On Sat, May 26, 2012 at 11:28 AM, Steve Aquino
reply@reply.github.com
wrote:

> Ok sorry about that, I've never added a Wiki page to a group project - I
> thought I had to add it on mine and it would merge when it was pulled
> into the main project.  In any case I've added the page to the proper
> place.  One thing though:  I can get everything to work properly, but
> when I try to run a unit test, there are some weird bugs: calling
> create_account results in like 10-20 creations of the same account, but
> everything works as expected from the console as well as in development,
> so I'm not sure what's going on there.  Running bundle exec rake test
> from the wepay-rails directory results in a loading error that I haven't
> yet taken the time to dive into yet.  As I said before, I'm currently
> using my version of the gem and having no issues beyond the test suite.
> I'm adamant about TDD, so it bothers me that my tests are running
> weird.  The changes I made are pretty trivial, so hopefully it's just
> something silly on my test suite I'm not seeing.
> 
> Thanks much for the RubyMine license!  I'm using Aptana Studio now and
> it's very buggy, so hopefully a more popular IDE will be better!
> 
> On 05/26/2012 01:27 AM, Adam Medeiros wrote:
> 
> > Hi Steve,
> > 
> >    I went into the wiki in the wepay-rails project, and I saw no
> > additional page(s) for your additions. Can you add them here?
> > https://github.com/adamthedeveloper/wepay-rails/wiki
> > 
> >    In the meantime, here is the rubymine license info:
> > 
> > IMPORTANT: THIS IS TO CERTIFY THE RIGHT TO USE THE JETBRAINS SOFTWARE
> > PRODUCT, GRANTED BY JETBRAINS S.R.O. UNDER THE TERMS AND CONDITIONS OF
> > THE LICENSE AGREEMENT INCLUDED WITH THE SOFTWARE. PLEASE SAVE A COPY
> > OF THIS EMAIL FOR FUTURE REFERENCES.
> > 
> > ========LICENSE DETAILS========
> > 
> > Type: Open Source License
> > Reference No*: LC-449227-D367410932
> > Date of Issue: 22 February 2012
> > Expiration Date: 21 February 2013
> > Number of Authorized Users: not limited
> > - Please quote this reference when contacting JetBrains
> > 
> > ===========LICENSEE============
> > 
> > Name: wepay-rails
> > Customer ID: 449227
> > Address:
> > 
> > =======SOFTWARE PRODUCT========
> > 
> > Product Name: RubyMine
> > Licensed Version: 3.2 and any new product release which is made
> > generally available before 21 February 2013
> > 
> > The software is shipped electronically and is available for download from:
> > http://www.jetbrains.com/ruby/download/
> > 
> > =========INSTALLATION==========
> > 
> > Run RubyMine and follow the Installation Wizard's instructions. To
> > register for use of the software or change your existing registration
> > details, go to Help/Register menu of the software and enter the
> > included below the User Name and License Key(s) into the registration
> > dialog:
> > 
> > User Name: wepay-rails
> > 
> > ===== LICENSE BEGIN =====
> > 449227-22022012
> > 00002kDp"kwBiA2!AXNOUh7DmilAWN
> > eIM1DY4NjiIQ5bZ6StmgDuuedtK9Rp
> > uJ5eCOokAKtGLdNDTU7dfbFe7pEHaf
> > ===== LICENSE END =====
> > 
> > ===DOCUMENTATION AND SUPPORT===
> > 
> > RubyMine documentation:
> > http://www.jetbrains.com/ruby/documentation/
> > 
> > Available support resources:
> > http://www.jetbrains.com/support/
> > 
> > Technical support contact:
> > support@jetbrains.com
> > 
> > Contact for the license renewal requests:
> > opensource@jetbrains.com
> > 
> > For questions, please contact:
> > sales@jetbrains.com
> > 
> > JetBrains Sales Team
> > http://www.jetbrains.com
> > "Develop with pleasure!"
> > 
> > Enjoy!
> > 
> > Adam
> > 
> > On Fri, May 25, 2012 at 9:33 PM, Steve Aquino
> > reply@reply.github.com
> > wrote:
> > 
> > > Ok added the wiki page and made another minor adjustment.  I had to
> > > update the gemspec and version again for the change but I made typo in
> > > the commit message; it still says version 2.2.6 but it is now 2.2.7, so
> > > I apologize for any confusion.
> > > 
> > > On 05/25/2012 03:49 PM, Adam Medeiros wrote:
> > > 
> > > > FANTASTIC!  All I ask is add an entry to the Wiki showing us all how to use your new feature.  As soon as that is in place, I'll pull your changes and send you a rubymine key!
> > > > 
> > > > Thanks!!
> > > > 
> > > > Adam
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > 
> > > > ## https://github.com/adamthedeveloper/wepay-rails/pull/10#issuecomment-5942081
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/adamthedeveloper/wepay-rails/pull/10#issuecomment-5944303
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/adamthedeveloper/wepay-rails/pull/10#issuecomment-5948726

## 

A.R. Medeiros

**Pull request merged**
